name: ESP32 Build

on:
  push:
    paths:
      - '**.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PlatformIO
        uses: platformio/github-actions@v3
        with:
          platformio_version: latest
      - name: Build firmware.bin
        run: |
          pio run -e esp32s3
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/esp32s3/firmware.bin
