name: ESP32 Build

on:
  push:
    paths:
      - '**.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          pip install -U platformio

      - name: Build firmware
        run: |
          pio run -e esp32s3

      - name: Upload firmware.bin
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32s3/firmware.bin
