name: ESP32 Build

on:
  push:
    paths:
      - '**.ino'
      - 'platformio.ini'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          pip install -U platformio

      - name: Build firmware
        run: |
          pio run -e esp32s3

      - name: Upload all firmware files
        uses: actions/upload-artifact@v4
        with:
          name: firmware-files
          path: |
            .pio/build/esp32s3/firmware.bin
            .pio/build/esp32s3/bootloader.bin
            .pio/build/esp32s3/partitions.bin
